# Generated by Django 6.0.1 on 2026-02-03 03:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogmodel_item_available_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='date_of_update',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='date_of_post',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
